<?php
//final class A { // Klasa B nie może dziedziczyć po klasie A
class A {
//    final public function test() { // Powoduje błąd w klasie B - nie można dziedziczyć metody, która jest final
    public $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function __toString()
    {
        return "My name is: ".$this->name;
    }

    public function test() {
        echo "class A test method <br>";
    }
}

class B extends A {
    public function test()
    {
        parent::test(); // TODO: Change the autogenerated stub
        echo "class B test method <br>";
    }
}

$a = new A('Jacek');
echo $a;
echo "<br>";

$b = new B('Jacek 1');
$b->test();

?>